name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set env
      run: echo "JAVA_TOOL_OPTIONS=$(echo -Djdk.lang.Process.launchMechanism=vfork)" >> $GITHUB_ENV
    - name: Setup JdK 17
    - uses: ./.github/shared_actions/jbr/setup_jbr17
  
      with:
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
