name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout JetBrains Setup
      uses: actions/checkout@v4
      with:
          repository: jansorg/github-actions-jbr-setup
          path: .github/shared_actions/jbr

    - name: Install JetBrains Runtime
      uses: ./.github/shared_actions/jbr/setup_jbr21


    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
